### ISSUE TITLE
Array passed as argument is shorten

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#21]
The following code:

> MODULE Test;
> IMPORT Out;
> VAR
>     str : ARRAY 25 OF CHAR;
> 
> PROCEDURE Capacity(str : ARRAY OF CHAR): LONGINT;
> BEGIN RETURN LEN(str)
> END Capacity;
> 
> PROCEDURE CapacityVar(VAR str : ARRAY OF CHAR): LONGINT;
> BEGIN RETURN LEN(str)
> END CapacityVar;
> 
> BEGIN
>     Out.Long(LEN(str), 0); Out.Ln();
>     Out.Long(Capacity(str), 0); Out.Ln();
>     Out.Long(CapacityVar(str), 0); Out.Ln();
>     str := "test";
>     Out.Long(LEN(str), 0); Out.Ln();
>     Out.Long(Capacity(str), 0); Out.Ln();
>     Out.Long(CapacityVar(str), 0); Out.Ln()
> END Test.

Outputs:

> 25
> 25
> 25
> 25
> 5
> 5

The array seems to be changed when passed as argument.

**Comment by zaskar9** [comment]
This is a known issue. I mentioned the problem when talking about the `COPY` procedures. The current implementation copies the entire array struct and thus "updates" the length of the array as well. In your examples, this happens when the array is passed as a non-variable parameter. In this case, the compiler will generate a copy and pass a pointer to that copy to the `Capacity` procedure.

As I mentioned elsewhere, I am not entirely happy with the current internal representation of arrays and plan to change it (again). This issue is precisely one of the reasons why I am not happy with it. Therefore, I propose that your example becomes a unit test that will help verify whether the planned refactoring will solve this issue down the line.

**Comment by zaskar9** [comment]
This has been fixed in the latest version of `oberon-lang`. Array and string assignment is now handled much more elaborately (and, hopefully, correctly) by CodeGen.
