### ISSUE TITLE
Report for Oberon compiler on x86_64 GNU/Linux

### ISSUE THREAD

**Issue by iadenisov** [zaskar9/oberon-lang#5]
I have checked Oberon compiler.
Hello World with LLVM backend is working fine.

```
Linux Mint 21.2 Cinnamon
Linux laptop 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
cmake (3.22.1-1ubuntu1.22.04.1)
libboost-all-dev (1.74.0.3ubuntu7)
llvm (1:14.0-55~exp2)
clang (1:14.0-55~exp2)
```

```
sudo apt install cmake llvm libboost-all-dev clang
cmake src
make
cp test/oberon/HelloWorld.Mod ./liboberon/
mv oberon-lang ./liboberon/
cd liboberon/
./oberon-lang --filetype ll Out.Mod
./oberon-lang --filetype ll HelloWorld.Mod
clang -o hello.elf Out.ll HelloWorld.ll
./hello.elf 
Hoi Niklaus!
```

**Comment by zaskar9** [comment]
Many thanks for this report! I will close the issue, since your report is the "opposite" of an issue! 😎

Nevertheless, let me point out a couple of things that might be of interest to you.
- Before merging code into the main branch, I typically test it on macOS (clang toolchain), Ubuntu (GNU toolchain), and Windows (MSVC toolchain), both on x64 and arm64. Since this is a toy/teaching project, I don't expect all functionality to work on all platforms perfectly, but there shouldn't be any major show-stoppers.
- There are utility Makefiles in the the `liboberon` and the `oberon/test` directory that help with compiling and linking the (beginnings of an) Oberon library and individual modules. The Makefiles assume the OS-toolchaing pairings mentioned in the previous point.
- In the long-term, it is the plan to replace these Makefiles by toolchain classes, following the example of the clang frontend.
- As you will notice, my Oberon compiler is far from perfect. There are many ways how people can help. Of course, I am always grateful for pull requests with new or improved functionality for the compiler itself. For example, I'm currently working on properly integrating the JIT functionality that has been sketched in one of the open pull requests.
- Another way to contribute to `oberon-lang` is by submitting test modules, ideally ones that do not (but should) compile. The test modules I currently use are all written by me or ChatGPT. Therefore, if I didn't think of something when I wrote the compiler, I surely didn't think about it when I wrote the test module. 🤓
